# Generated by Django 6.0.5 on 2026-05-24 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watercraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('boat', 'Boat'), ('jet_ski', 'Jet Ski'), ('yacht', 'Yacht'), ('speed_boat', 'Speed Boat')], default='boat', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='watercraft/')),
                ('image_url', models.URLField(blank=True, help_text='Optional external image URL fallback')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('passenger_capacity', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, help_text='Dock or marina location', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
